# Site settings
title: FridayQ&A 中文版
description: "FridayQ&A 中文版"
url: "http://idevqa.github.io/FridayQA/"
author:
  name: "Friday Q&A 中文"
  email: "gua@desgard.com"
  url: "http://idevqa.github.io/FridayQA/"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
